
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getUsageStats() : Promise<Result<UsageStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_usage_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async interpreterStart() : Promise<Result<InterpreterRoom, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("interpreter_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async interpreterStop() : Promise<void> {
    await TAURI_INVOKE("interpreter_stop");
},
async interpreterStatus() : Promise<InterpreterStatus> {
    return await TAURI_INVOKE("interpreter_status");
},
/**
 * Publica una línea del guía: traduce a cada idioma de oyente activo con el
 * motor local y la emite. En Fase 1/2 el texto viene del input de prueba o
 * del micrófono; el idioma de origen se asume el de la app.
 */
async interpreterPublish(text: string, sourceLang: string) : Promise<void> {
    await TAURI_INVOKE("interpreter_publish", { text, sourceLang });
},
async interpreterSetSourceLang(lang: string) : Promise<void> {
    await TAURI_INVOKE("interpreter_set_source_lang", { lang });
},
async interpreterSetListening(on: boolean) : Promise<void> {
    await TAURI_INVOKE("interpreter_set_listening", { on });
},
async translatorSetLangs(langA: string, langB: string) : Promise<void> {
    await TAURI_INVOKE("translator_set_langs", { langA, langB });
},
async translatorSetListening(on: boolean) : Promise<void> {
    await TAURI_INVOKE("translator_set_listening", { on });
},
async translatorStatus() : Promise<TranslatorStatus> {
    return await TAURI_INVOKE("translator_status");
},
async conversationStart(mode: string) : Promise<ConversationStatus> {
    return await TAURI_INVOKE("conversation_start", { mode });
},
async conversationStop() : Promise<ConversationStatus> {
    return await TAURI_INVOKE("conversation_stop");
},
async conversationStatus() : Promise<ConversationStatus> {
    return await TAURI_INVOKE("conversation_status");
},
async conversationReset() : Promise<ConversationStatus> {
    return await TAURI_INVOKE("conversation_reset");
},
/**
 * Cierra la sesión y la convierte en documento con el motor local.
 * `converse` → nota limpia de la conversación; `listen` → acta con acuerdos.
 */
async conversationFinish() : Promise<Result<SessionDoc, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_finish") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lee un texto en voz alta con la cascada de motores de Escriba:
 * 1) Voz neural incluida (sherpa-onnx + Piper es_MX), si está instalada y la
 * app está en español (la voz es de español; otros idiomas caen al paso 2).
 * 2) `say` de macOS (la voz del sistema, que sí ve las Premium/Mejorada que
 * el webview no expone).
 * 3) `false` → el frontend usa speechSynthesis como último respaldo.
 */
async conversationSpeak(text: string, engine: string) : Promise<boolean> {
    return await TAURI_INVOKE("conversation_speak", { text, engine });
},
/**
 * Detiene la lectura en voz alta en curso (cualquier motor).
 */
async conversationSpeakStop() : Promise<void> {
    await TAURI_INVOKE("conversation_speak_stop");
},
/**
 * Estado de la voz neural incluida (para la tarjeta de instalación).
 */
async ttsStatus() : Promise<boolean> {
    return await TAURI_INVOKE("tts_status");
},
/**
 * Descarga e instala la voz neural (runtime + voz, ~95 MB, SHA256 pinneado).
 * Emite `tts-setup-progress` durante la descarga.
 */
async ttsSetup() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tts_setup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ¿Está lista la voz neural incluida para este idioma? (Intérprete de
 * reuniones: inglés y español tienen voz; otros idiomas usan la del sistema.)
 */
async interpreterVoiceStatus(lang: string) : Promise<boolean> {
    return await TAURI_INVOKE("interpreter_voice_status", { lang });
},
/**
 * Descarga la voz neural incluida para el idioma del Intérprete (runtime
 * compartido + voz, SHA256 pinneado). Emite `tts-setup-progress`.
 */
async interpreterVoiceSetup(lang: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("interpreter_voice_setup", { lang }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manos libres para los modos de escucha: abre el micrófono y deja que el
 * VAD corte cada intervención en los silencios; cada segmento se transcribe
 * y entra como turno, sin atajo. (Solo escucha: en Conversar la voz de la
 * respuesta se re-capturaría a sí misma.)
 */
async conversationHandsFree(on: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_hands_free", { on }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Suma a la sesión lo que suena en el computador (la otra parte de una
 * reunión Zoom/Meet, un video). El mismo VAD del micrófono (Silero) separa
 * voz de música/silencio; cada intervención se corta en las pausas (o a los
 * 25 s si nadie pausa, como en un podcast), se transcribe local y entra como
 * turno de "Otros". Solo modos de escucha.
 */
async conversationSystemAudio(on: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_system_audio", { on }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ¿Este equipo puede capturar el audio del sistema? (macOS 13+, Apple Silicon)
 */
async systemAudioSupported() : Promise<boolean> {
    return await TAURI_INVOKE("system_audio_supported");
},
/**
 * ¿Está concedido el permiso de Grabación de pantalla? (panel de permisos)
 */
async systemAudioPermission() : Promise<boolean> {
    return await TAURI_INVOKE("system_audio_permission");
},
/**
 * Intérprete de reuniones (idea de John Walter, comunidad): con esto activo,
 * los turnos de "Otros" que lleguen en `foreign` se traducen al idioma de la
 * app antes de mostrarse. Requiere el motor local (igual que el Traductor).
 */
async conversationSystemTranslate(on: boolean, foreign: string) : Promise<boolean> {
    return await TAURI_INVOKE("conversation_system_translate", { on, foreign });
},
/**
 * Voz del Intérprete por un dispositivo de salida concreto (el remate de la
 * idea de John Walter): renderiza el texto con la mejor voz instalada del
 * idioma y lo reproduce en ese dispositivo. Con un micrófono virtual
 * (BlackHole) elegido aquí y como micrófono de la reunión, la otra persona
 * escucha tu dictado ya traducido. Solo macOS (como el audio del sistema).
 */
async conversationSpeakVia(text: string, lang: string, device: string, gender: string, engine: string) : Promise<boolean> {
    return await TAURI_INVOKE("conversation_speak_via", { text, lang, device, gender, engine });
},
/**
 * ¿Está el micrófono virtual instalado? (aparece como dispositivo de salida).
 */
async virtualMicInstalled() : Promise<boolean> {
    return await TAURI_INVOKE("virtual_mic_installed");
},
/**
 * Descarga el paquete oficial (SHA256 verificado, descartado si no calza) y
 * lo instala con el diálogo nativo de privilegios de macOS. Devuelve false
 * si el usuario canceló el diálogo (no es un error, no hay drama). Los
 * errores son claves estables para que el frontend traduzca (auditoría #14).
 */
async virtualMicInstall() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("virtual_mic_install") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Desinstala el micrófono virtual (auditoría #13: antes salir exigía `sudo rm`
 * a mano). Borra el driver de BlackHole y reinicia coreaudiod, con el diálogo
 * de privilegios de macOS. false = el usuario canceló el diálogo.
 */
async virtualMicUninstall() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("virtual_mic_uninstall") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Guarda (o borra) la carpeta del vault de Obsidian en los ajustes.
 * 
 * La carpeta se contiene al home del usuario. El comentario de cabecera decía
 * que "la ruta la consiente el usuario con el selector de carpeta", pero el
 * backend no puede comprobar que la cadena venga de verdad del selector: sin
 * esta validación, cualquiera que pudiera escribir en los ajustes convertía
 * este comando en una escritura de archivos `.md` en cualquier parte del disco.
 */
async setObsidianVault(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_obsidian_vault", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ruta del vault configurada (cadena vacía si no hay).
 */
async getObsidianVault() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_obsidian_vault") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Subcarpeta de notas. Se guarda ya saneada, para que lo que se muestre en
 * Ajustes sea exactamente lo que se va a usar al exportar.
 */
async setObsidianNotesFolder(folder: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_obsidian_notes_folder", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Escribe `content` como nota Markdown titulada `title` en el vault. Devuelve
 * la ruta del archivo creado. Falla con un mensaje claro si no hay vault
 * configurado o la carpeta ya no existe (para que el frontend pida elegirla).
 */
async exportToObsidian(title: string, content: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_to_obsidian", { title, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Convierte menciones del contenido en enlaces `[[Nota]]` usando SOLO los
 * nombres de archivo del vault (jamás se leen contenidos: privacidad y
 * velocidad). Corre detrás del diálogo de vista previa: el usuario ve y
 * edita el resultado ANTES de que nada toque el vault.
 * 
 * Reglas del matcher (blindaje matcher-includes-substring):
 * - límites de palabra Unicode: `Ana.md` no enlaza dentro de "Analía"
 * - candidatos por longitud DESC: "Plan Premium" gana sobre "Plan"
 * - mínimo 3 caracteres; insensible a mayúsculas (alias `[[Nota|mención]]`),
 * SENSIBLE a tildes ("mas" no enlaza a `Más.md`)
 * - zonas excluidas: front matter, código (bloques y spans), URLs y enlaces
 * ya existentes
 * 
 * Sin vault configurado (o inválido) devuelve el contenido intacto: el
 * enlazado es un extra del export, no una condición.
 */
async linkObsidianMentions(content: string) : Promise<Result<LinkedResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("link_obsidian_mentions", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bandeja de entrada diaria (PRP-007, Fase 3): agrega un dictado al final de
 * `Inbox YYYY-MM-DD.md` como entrada con hora. Append puro: jamás reordena ni
 * reescribe lo anterior. Misma disciplina de revalidación que el export (el
 * vault se comprueba EN CADA operación, no solo al guardar el ajuste).
 */
async appendToObsidianInbox(content: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("append_to_obsidian_inbox", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpStart() : Promise<Result<McpStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpStop() : Promise<void> {
    await TAURI_INVOKE("mcp_stop");
},
async mcpStatus() : Promise<McpStatus> {
    return await TAURI_INVOKE("mcp_status");
},
/**
 * Alterna la grabación para un campo. El primer llamado arranca; el segundo
 * para y procesa (el coordinador trabaja en modo toggle). Marca el desvío a
 * campo para que el texto no se pegue en la app enfocada.
 */
async fieldDictationToggle() : Promise<void> {
    await TAURI_INVOKE("field_dictation_toggle");
},
/**
 * Enciende o apaga el Dictado libre desde la UI.
 */
async freeDictationSet(on: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("free_dictation_set", { on }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ¿Está activo? (para el pill de modo activo y el estado del tray)
 */
async freeDictationStatus() : Promise<boolean> {
    return await TAURI_INVOKE("free_dictation_status");
},
/**
 * Encola archivos y arranca su transcripción en un worker. Devuelve los ids.
 * 
 * La ruta se valida además de la extensión. Antes el único filtro era el sufijo
 * del archivo, así que este comando transcribía CUALQUIER audio o video del
 * disco y devolvía el texto en `studio_jobs`: un oráculo de lectura para un
 * frontend comprometido. Se guarda la ruta ya canonicalizada, para que
 * `studio_retranscribe` reabra la que se validó y no la cadena original.
 */
async studioEnqueue(paths: string[]) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("studio_enqueue", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async studioJobs() : Promise<StudioJob[]> {
    return await TAURI_INVOKE("studio_jobs");
},
/**
 * Devuelve una URL privada y efímera para reproducir el medio de un job. La
 * ruta no cruza a JavaScript y el protocolo vuelve a validar id, estado y ruta
 * en cada petición/rango.
 */
async studioPlaybackUrl(id: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("studio_playback_url", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-transcribe un job ya terminado con OTRO modelo. Re-decodifica el archivo
 * original (nunca se copió a la app, así que debe seguir en su ruta) y corre la
 * transcripción de nuevo. `model_id = None` usa el modelo por defecto.
 */
async studioRetranscribe(id: number, modelId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("studio_retranscribe", { id, modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async studioRemoveJob(id: number) : Promise<void> {
    await TAURI_INVOKE("studio_remove_job", { id });
},
/**
 * Exporta un job terminado al formato pedido y devuelve el contenido para
 * que el frontend lo guarde con el diálogo nativo.
 */
async studioExport(id: number, format: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("studio_export", { id, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Exporta un job y lo ESCRIBE en la ruta que el usuario eligió con el diálogo
 * nativo. La escritura ocurre en el backend (std::fs), no en el webview, para
 * que la app no necesite permisos de escritura al home en la capa de la UI.
 * 
 * El backend no puede comprobar que `dest` venga de verdad del diálogo nativo,
 * así que además contiene la ruta al home del usuario: sin eso, este comando
 * escribía bytes arbitrarios en cualquier ruta absoluta (`~/.zshrc`, un
 * LaunchAgent, `~/.ssh/authorized_keys`).
 */
async studioExportTo(id: number, format: string, dest: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("studio_export_to", { id, format, dest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume la transcripción con el motor de IA local (misma cascada del phraser).
 */
async studioSummarize(id: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("studio_summarize", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocalLlmStatus() : Promise<LocalLlmStatus> {
    return await TAURI_INVOKE("get_local_llm_status");
},
/**
 * Descarga runtime + modelo con progreso, verifica SHA256 y deja el motor
 * precalentado. Idempotente: lo ya instalado y verificado se salta.
 */
async setupLocalLlm() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("setup_local_llm") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async askPlumin(question: string) : Promise<Result<PluminHelpResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ask_plumin", { question }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePttSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ptt_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeReviewBeforePasteSetting(on: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_review_before_paste_setting", { on }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeFaithfulModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_faithful_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUiThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ui_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUiScaleSetting(scale: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ui_scale_setting", { scale }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeHighContrastSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_high_contrast_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeColorblindAssistSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_colorblind_assist_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeCalmModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_calm_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAlwaysShowFocusSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_always_show_focus_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayStyleSetting(style: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_style_setting", { style }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExtraRecordingBufferSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_extra_recording_buffer_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslationTargetLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translation_target_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTextReplacements(rules: TextReplacement[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_text_replacements", { rules }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeNoiseSuppressionSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_noise_suppression_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Guardar o no el .wav de cada dictado. Apagado por omisión: ver
 * `settings::default_save_audio_recordings`.
 */
async changeSaveAudioRecordingsSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_save_audio_recordings_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePauseMediaOnDictateSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_pause_media_on_dictate_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMcpAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mcp_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister a binding while the user is editing it in the UI.
 * This avoids firing the action while keys are being recorded.
 */
async suspendBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register the binding after the user has finished editing.
 */
async resumeBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLazyStreamCloseSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_lazy_stream_close_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVadEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDictatedEmojisSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_dictated_emojis_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSpokenNumeralsSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_spoken_numerals_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeNumeralsSpreadsheetAutoSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_numerals_spreadsheet_auto_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShowWhatsNewOnUpdateSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_whats_new_on_update_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persiste el motor de lectura de una herramienta. El nombre del ajuste está
 * cerrado a esta lista para que el comando no se convierta en un escritor
 * genérico de configuración.
 */
async changeVoiceEngineSetting(setting: string, engine: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_voice_engine_setting", { setting, engine }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhatsNewLastSeenVersionSetting(version: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whats_new_last_seen_version_setting", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeAcceleratorSetting(accelerator: TranscribeAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOrtAcceleratorSetting(accelerator: OrtAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ort_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeGpuDevice(device: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_gpu_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return which accelerators and GPU devices are available for this build.
 * 
 * First-call cost is dominated by enumerating GPU devices through the
 * transcribe.cpp Metal/Vulkan backend, which loads dynamic libraries and
 * probes hardware. Run it on the blocking pool so the webview thread
 * stays responsive — see also the startup pre-warm in `lib.rs`.
 */
async getAvailableAccelerators() : Promise<AvailableAccelerators> {
    return await TAURI_INVOKE("get_available_accelerators");
},
/**
 * Start key recording mode
 */
async startHandyKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_handy_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopHandyKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_handy_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async isPortable() : Promise<boolean> {
    return await TAURI_INVOKE("is_portable");
},
/**
 * Servidor gráfico en uso, para que el onboarding pueda avisar en Linux.
 * 
 * Devuelve `"wayland"`, `"other"` o `"not_linux"`. La app ya detectaba Wayland
 * para elegir cómo escribir en el portapapeles (`utils::is_wayland`), pero esa
 * información nunca llegaba a la interfaz: el onboarding trataba Linux como
 * "plataforma no soportada" y se saltaba entero, así que quien usa Wayland se
 * quedaba sin saber por qué su atajo global podía no responder.
 * 
 * `"other"` en vez de `"x11"` a propósito: si no hay `WAYLAND_DISPLAY` ni
 * `XDG_SESSION_TYPE=wayland`, lo único que se puede afirmar es que no es
 * Wayland, no que sea X11.
 */
async linuxDisplayServer() : Promise<string> {
    return await TAURI_INVOKE("linux_display_server");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ajustes para la UI, con las API keys enmascaradas.
 * 
 * Este comando se llama en cada lectura de ajustes, así que antes mandaba
 * todas las claves de los proveedores LLM en texto plano al webview una y otra
 * vez. El backend ya tiene las claves de verdad cuando las necesita (las lee de
 * `get_settings` en `actions.rs`), y la escritura pasa por `change_*`, así que
 * el frontend nunca necesitó el valor real.
 */
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-scan local sources (custom models dir + shared HF cache) for models added
 * since launch
 */
async rescanLocalModels() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rescan_local_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sugerencias de diccionario a partir del historial (idea de Benjamín
 * Carreño, comunidad 16-jul-2026): detecta palabras "inusuales" que el
 * usuario repite en sus dictados — nombres propios, marcas, jerga técnica —
 * y las propone para Palabras personalizadas, donde el post-proceso las
 * respeta siempre. Heurística local, cero red: mayúscula fuera de inicio de
 * frase, mezcla de mayúsculas o dígitos, repetida al menos 3 veces.
 */
async suggestCustomWords() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_custom_words") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pegar el texto pendiente donde está el cursor y cerrar la revisión.
 * El overlay es un panel sin foco (NSPanel/focusable=false), así que la app
 * destino sigue siendo la del usuario; el pequeño delay da margen igual.
 */
async reviewConfirm() : Promise<void> {
    await TAURI_INVOKE("review_confirm");
},
/**
 * Descartar el texto pendiente sin pegar nada.
 */
async reviewDiscard() : Promise<void> {
    await TAURI_INVOKE("review_discard");
},
/**
 * Copia el texto pendiente al portapapeles y cierra la revisión.
 * 
 * La auditoría pedía poder EDITAR aquí, pero el overlay es un panel no
 * enfocable a propósito (así la app de destino conserva el foco y el pegado
 * llega a donde el usuario estaba escribiendo). Un campo de texto ahí dentro
 * no podría recibir teclado, y hacer el panel enfocable rompería justo lo que
 * hace útil a la feature.
 * 
 * Copiar es la salida que sí respeta ese diseño: si el motor entendió mal, el
 * usuario se lleva el texto y lo arregla en su propio editor, sin tener que
 * repetir la frase entera.
 */
async reviewCopy() : Promise<void> {
    await TAURI_INVOKE("review_copy");
},
/**
 * Alternativa por TECLADO al dictado: procesa un texto escrito con el mismo
 * motor de IA y devuelve el resultado.
 * 
 * Toda la corrección, traducción y tonos de Escriba pasaban por hablar. Alguien
 * que en ese momento no pueda usar la voz (una oficina compartida, afonía, una
 * discapacidad del habla) no tenía forma de usar el motor local que la app ya
 * tiene instalado, aunque la infraestructura estuviera entera.
 * 
 * Devuelve el texto en pantalla en vez de pegarlo: cuando la ventana principal
 * tiene el foco, la aplicación de destino ya lo perdió, así que pegar iría al
 * sitio equivocado. El usuario copia el resultado y lo lleva a donde quiera.
 */
async processTypedText(text: string, action: TypedTextAction, targetLang: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("process_typed_text", { text, action, targetLang }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-transcribe una entrada del historial. Si `model_id` viene con valor, usa
 * ESE modelo (sin tocar el modelo por defecto del usuario: se restaura en el
 * próximo dictado). Si es `None`, usa el modelo seleccionado actual. Sirve para
 * "misma grabación, más precisión con otro modelo".
 */
async retryHistoryEntryTranscription(id: number, modelId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_history_entry_transcription", { id, modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks if the Mac is a laptop by detecting battery presence
 * 
 * This uses pmset to check for battery information.
 * Returns true if a battery is detected (laptop), false otherwise (desktop)
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
historyUpdatePayload: HistoryUpdatePayload,
streamPhaseEvent: StreamPhaseEvent,
streamTextEvent: StreamTextEvent
}>({
historyUpdatePayload: "history-update-payload",
streamPhaseEvent: "stream-phase-event",
streamTextEvent: "stream-text-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Tonos por app: si la app activa al dictar coincide con `app_match`
 * (subcadena, sin distinguir mayúsculas), el post-proceso usa `prompt_id`
 * en vez de la plantilla global. WhatsApp casual, Mail formal, etc.
 */
export type AppContextRule = { app_match: string; prompt_id: string }
export type AppSettings = { 
/**
 * Internal settings schema marker for one-time migrations. Fresh installs
 * start at the current version; existing stores missing this key are
 * treated as version 0 and migrated forward.
 */
settings_schema_version?: number; bindings: Partial<{ [key in string]: ShortcutBinding }>; push_to_talk: boolean; audio_feedback: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; 
/**
 * Apariencia de la interfaz: "system" (sigue a macOS), "light" o "dark".
 */
ui_theme?: string; 
/**
 * Escala del texto de toda la interfaz, en porcentaje (90-130).
 * Accesibilidad: ojos cansados o vista reducida sin tocar el sistema.
 */
ui_scale?: number; 
/**
 * Accesibilidad visual: tinta y bordes reforzados, sin cristal difuminado.
 */
high_contrast?: boolean; 
/**
 * Accesibilidad visual: estados semánticos en par cian/violeta, que evita
 * el eje rojo/verde (la confusión más común del daltonismo).
 */
colorblind_assist?: boolean; 
/**
 * Modo Calma: sin animaciones ni transiciones, texto y espaciado ampliados,
 * superficies planas. Para dictar sin estímulos visuales.
 */
calm_mode?: boolean; 
/**
 * Anillo de foco también con el ratón, no solo al navegar con teclado.
 * Para quien pierde de vista dónde está parado dentro de la interfaz.
 */
always_show_focus?: boolean; 
/**
 * Motor de lectura por herramienta. La voz del sistema es el valor
 * inicial porque ganó la prueba A/B; la incluida sigue disponible como
 * alternativa explícita y local.
 */
conversation_voice_engine?: string; interpreter_voice_engine?: string; read_selection_voice_engine?: string; 
/**
 * Subcarpeta dentro del vault donde aterrizan las notas. Vacío = raíz.
 */
obsidian_notes_folder?: string; obsidian_link_mentions?: boolean; obsidian_index_note?: boolean; obsidian_daily_inbox?: boolean; 
/**
 * Revisar antes de pegar: el dictado normal se muestra en el overlay
 * (Pegar / Descartar / corregir dictando) en vez de pegarse directo.
 */
review_before_paste?: boolean; 
/**
 * Dictado normal sin transformaciones: conserva el texto que entrega el
 * motor y omite diccionario difuso, limpieza lingüística, tonos por app,
 * numerales, emojis y reemplazos. Los atajos explícitos de Escritura
 * Inteligente, traducción y edición conservan su comportamiento.
 */
faithful_mode_enabled?: boolean; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; show_whats_new_on_update?: boolean; 
/**
 * The app version whose What's New the user has already seen. Fresh installs
 * default to the current version (nothing is "new" to them). Existing users
 * upgrading from before this key existed are blanked by the migration so they
 * see the current release's notes — see `apply_settings_migrations`.
 */
whats_new_last_seen_version?: string; selected_model?: string; onboarding_completed?: boolean; always_on_microphone?: boolean; selected_microphone?: string | null; clamshell_microphone?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; dictated_emojis_enabled?: boolean; spoken_numerals_enabled?: boolean; numerals_spreadsheet_auto?: boolean; overlay_position?: OverlayPosition; debug_mode?: boolean; log_level?: LogLevel; custom_words?: string[]; model_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; history_limit?: number; recording_retention_period?: RecordingRetentionPeriod; 
/**
 * Escribir el .wav de cada dictado en disco. Apagado por omisión: ver
 * `default_save_audio_recordings`.
 */
save_audio_recordings?: boolean; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; post_process_provider_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: SecretMap; post_process_models?: Partial<{ [key in string]: string }>; post_process_prompts?: LLMPrompt[]; 
/**
 * Carpeta del vault de Obsidian (o cualquier carpeta de notas Markdown)
 * donde "Enviar a Obsidian" escribe el documento. Vacío = sin configurar;
 * se pide con el selector de carpeta la primera vez.
 */
obsidian_vault_path?: string; 
/**
 * Tonos por app: activa el override de plantilla según la app activa.
 */
app_context_enabled?: boolean; 
/**
 * Reglas app → plantilla (evaluadas en orden; gana la primera que coincide).
 */
app_context_rules?: AppContextRule[]; post_process_selected_prompt_id?: string | null; translation_target_language?: string; mute_while_recording?: boolean; append_trailing_space?: boolean; app_language?: string; experimental_enabled?: boolean; lazy_stream_close?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; paste_delay_ms?: number; typing_tool?: TypingTool; external_script_path: string | null; custom_filler_words?: string[] | null; transcribe_accelerator?: TranscribeAcceleratorSetting; ort_accelerator?: OrtAcceleratorSetting; transcribe_gpu_device?: number; extra_recording_buffer_ms?: number; vad_enabled?: boolean; 
/**
 * Which recording overlay to show: None / Minimal / Live. Streaming mode is
 * not gated on this — that follows model capability. Migrated from the old
 * `overlay_position` (position `none` → style `None`).
 */
overlay_style?: OverlayStyle; 
/**
 * Reglas de buscar/reemplazar aplicadas al texto final tras transcribir.
 */
text_replacements?: TextReplacement[]; 
/**
 * Supresión de ruido de fondo del micrófono antes de transcribir.
 */
noise_suppression?: boolean; 
/**
 * Pausar la reproducción de medios (Música/Spotify) mientras dictas.
 */
pause_media_on_dictate?: boolean; 
/**
 * Arrancar el servidor MCP (Agentes) automáticamente al abrir la app.
 */
mcp_autostart?: boolean }
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type AvailableAccelerators = { transcribe: string[]; ort: string[]; gpu_devices: GpuDeviceOption[] }
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
export type ConversationStatus = { listening: boolean; 
/**
 * "converse" | "listen"
 */
mode: string; turns: Turn[]; 
/**
 * Los tres modos vivían SOLO como estáticos en el backend y como
 * `useState(false)` en la vista, sin nada que los reconciliara: este struct
 * se diseñó para los turnos y nunca se le pidió responder por los modos.
 * 
 * El síntoma era de privacidad: salías de Sesiones con el audio del sistema
 * encendido, volvías, y el interruptor aparecía apagado mientras el backend
 * seguía capturando. Y `conversation_stop` los apaga los tres pero devolvía
 * un estado que no los mencionaba, así que la interfaz tampoco se enteraba.
 */
hands_free: boolean; system_audio: boolean; sys_translate: boolean }
export type CustomSounds = { start: boolean; stop: boolean }
export type EngineType = 
/**
 * Any GGML/GGUF model loaded through transcribe-cpp (Whisper, Parakeet,
 * Voxtral, Qwen3-ASR, Nemotron, …). The architecture is auto-detected from
 * the file, so this one variant covers the whole transcribe-cpp family.
 */
"TranscribeCpp" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere"
export type GpuDeviceOption = { id: number; name: string; total_vram_mb: number }
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_requested: boolean }
export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
export type InterpreterRoom = { code: string; url: string; qr_svg: string; port: number }
export type InterpreterStatus = { running: boolean; listeners: number; active_languages: string[] }
export type JobStatus = "pending" | "processing" | "done" | "error"
export type KeyboardImplementation = "tauri" | "handy_keys"
export type LLMPrompt = { id: string; name: string; prompt: string }
/**
 * Resultado de convertir menciones en enlaces `[[...]]`.
 */
export type LinkedResult = { content: string; 
/**
 * Cuántos enlaces se insertaron (para el hint del diálogo).
 */
links: number }
export type LocalLlmStatus = { runtime_installed: boolean; model_installed: boolean; engine_running: boolean; setup_in_progress: boolean; model_file: string }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
/**
 * Una llamada a tool en el feed de actividad reciente.
 */
export type McpActivity = { tool: string; ms: number; seconds_ago: number }
/**
 * Un agente que se ha conectado (Claude Code, Cursor, ...).
 */
export type McpClient = { name: string; version: string; seconds_ago: number }
export type McpStatus = { running: boolean; port: number; url: string | null; uptime_seconds: number; total_calls: number; tool_counts: McpToolCount[]; activity: McpActivity[]; clients: McpClient[] }
/**
 * Conteo de llamadas por tool.
 */
export type McpToolCount = { name: string; count: number }
export type ModelInfo = { id: string; name: string; description: string; filename: string; source: ModelSource; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; 
/**
 * Editorial position within the recommended set (1 = the default we put
 * in front of a new user). The UI needs it to badge the top pick: without
 * it, our #1 fell through every "why does this stand out" rule and showed
 * nothing, while a slower model wore "best quality".
 */
recommended_rank: number | null; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean; supports_streaming: boolean; supports_language_detection: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
/**
 * Where a model comes from and how Handy obtains it — the routing discriminant
 * for downloading and on-disk resolution.
 */
export type ModelSource = 
/**
 * Direct HTTP download from a URL (current blob.handy.computer hosting).
 */
{ Url: { url: string; 
/**
 * Expected SHA-256 for integrity verification; `None` skips it.
 */
sha256: string | null } } | 
/**
 * A file inside a Hugging Face Hub repo, fetched via hf-hub into the shared
 * HF cache (so other tools reuse it). The file within the repo is
 * [`ModelInfo::filename`].
 */
{ HuggingFace: { repo_id: string; revision: string } } | 
/**
 * Already present on disk — a user-provided custom model, or one discovered
 * in a shared cache. Nothing to download.
 */
"Local"
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_15"
export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm"
export type OverlayPosition = "top" | "bottom"
/**
 * Which recording overlay to display. `Minimal` and `Live` share one base
 * (the pill); `Live` grows into the panel that shows live transcription text.
 * `None` hides the overlay entirely. Decoupled from whether the model runs in
 * streaming mode (that is driven purely by model capability).
 */
export type OverlayStyle = "none" | "minimal" | "live"
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type PermissionAccess = "allowed" | "denied" | "unknown"
export type PluminHelpResponse = { topic: string; section: string; 
/**
 * `None` indica que la UI debe usar su respuesta i18n congelada.
 */
answer: string | null; used_local_engine: boolean }
export type PostProcessProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; models_endpoint?: string | null; supports_structured_output?: boolean }
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
export type SecretMap = Partial<{ [key in string]: string }>
/**
 * Documento final + ánimo general de la sesión (idea de Pedro Sánchez,
 * comunidad): Plumín entrega el acta con la carita acorde.
 */
export type SessionDoc = { text: string; 
/**
 * "positivo" | "neutral" | "tenso" (neutral si el modelo no lo marcó).
 */
mood: string }
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SoundTheme = "marimba" | "pop" | "custom"
/**
 * Phase of the streaming overlay card, emitted to drive its UI state.
 */
export type StreamPhase = 
/**
 * Receiving audio / live text (or waiting for the stream to begin). Rust
 * does not emit this today; the frontend starts in this phase and Rust only
 * emits transitions away from it.
 */
"listening" | 
/**
 * Finalizing or post-processing — show a spinner.
 */
"working"
/**
 * Emitted to switch the streaming overlay to a working spinner.
 */
export type StreamPhaseEvent = { phase: StreamPhase; 
/**
 * Present only when `phase` is `Working`.
 */
kind?: StreamWorkKind | null }
/**
 * Live transcription snapshot emitted to the overlay during a streaming run.
 * `committed` is the append-only, flicker-free prefix; `tentative` is the
 * volatile suffix the model may still rewrite.
 */
export type StreamTextEvent = { committed: string; tentative: string }
/**
 * Semantic kind of "working" phase, used to localize the spinner label.
 */
export type StreamWorkKind = "transcribing" | "polishing"
export type StudioJob = { id: number; file_name: string; status: JobStatus; progress: number; error: string | null; duration_s: number; paragraphs: string[]; 
/**
 * Líneas listas para la vista humana `[M:SS] texto`. Los segmentos crudos
 * siguen privados: la UI recibe solo lo que necesita para alternar la vista.
 */
timestamped_text: string[]; summary: string | null; 
/**
 * Modelo con el que se produjo esta transcripción (para mostrar el recibo
 * "mismo audio, modelo X" al re-transcribir). `None` = modelo por defecto.
 */
model_id: string | null; 
/**
 * Hubo tramos donde el modelo estaba adivinando (confianza media por debajo
 * del umbral). Sirve para avisar al usuario de que conviene repasar antes
 * de exportar, en vez de que descubra la alucinación en el subtítulo ya
 * publicado. `false` también cuando el motor no reporta confianza.
 */
low_confidence: boolean }
/**
 * Regla determinista de buscar/reemplazar que se aplica al texto final tras
 * transcribir (antes de pegar). `is_regex` interpreta `find` como expresión
 * regular; si el patrón es inválido, la regla se ignora sin romper nada.
 */
export type TextReplacement = { find: string; replace: string; is_regex?: boolean }
export type TranscribeAcceleratorSetting = "auto" | "cpu" | "gpu"
export type TranslatorStatus = { listening: boolean; lang_a: string; lang_b: string }
export type Turn = { 
/**
 * "user" | "assistant"
 */
role: string; text: string; 
/**
 * Segundos desde el inicio de la sesión (para mostrar mm:ss).
 */
at_secs: number }
/**
 * Qué hacer con un texto escrito a teclado.
 * 
 * Solo dos de los cuatro [`crate::actions::TranscribeMode`] tienen sentido por
 * aquí. `Edit` queda fuera a propósito: depende de la selección que captura el
 * Cmd/Ctrl+C sintético al empezar una edición por voz, así que desde un panel
 * de texto siempre encontraría el buffer vacío y caería en "no_selection".
 */
export type TypedTextAction = 
/**
 * Aplica el tono/plantilla configurada, igual que un dictado normal.
 */
"correct" | 
/**
 * Traduce al idioma de `translation_target_language`.
 */
"translate"
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"
export type UsageStats = { total_transcriptions: number; total_words: number; words_last_30_days: number; active_days_last_30: number; current_streak_days: number; 
/**
 * Minutos ahorrados vs teclear a 40 palabras/minuto (supuesto explícito
 * mostrado en la UI), descontando ~200 wpm de dictado efectivo.
 */
minutes_saved: number; 
/**
 * Palabras dictadas por día en los últimos 7 días, la más antigua primero
 * (el índice 6 es hoy). Mismo balde de día UTC que usa la racha: un
 * dictado nocturno puede caer en el día siguiente, y se prefiere esa
 * imprecisión conocida a tener dos nociones de "día" en la misma tarjeta.
 */
words_by_day: number[] }
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
